services:
  # Development service with hot reload (frontend only)
  load-calculator-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.node.json:/app/tsconfig.node.json:ro
      - ./tailwind.config.js:/app/tailwind.config.js:ro
      - ./postcss.config.js:/app/postcss.config.js:ro
      - /app/node_modules
      - /app/dist
      - /app/.vite
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=2000
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - API_BASE_URL=http://localhost:3004
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - api-server
    profiles:
      - dev

  # Fullstack development service (frontend + backend in one container)
  load-calculator-fullstack:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
      # No build arguments to prevent API key exposure in image layers
    ports:
      - "3003:3000"  # Frontend
      - "3001:3001"  # Backend API
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./api:/app/api:ro
      - ./server.js:/app/server.js:ro
      - ./server-dev.js:/app/server-dev.js:ro
      - ./.env.local:/app/.env.local:ro
      - /app/node_modules
      - /app/dist
      - /app/.vite
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=2000
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
      - API_BASE_URL=http://localhost:3001
      # Runtime API key injection (no exposure in image layers)
      # Variables will be loaded from .env.local file
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/", "&&", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - fullstack

  # Backend API server (separate container)
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3001"
    volumes:
      - ./api:/app/api:ro
      - ./server.js:/app/server.js:ro
      - ./server-dev.js:/app/server-dev.js:ro
      - ./.env.local:/app/.env.local:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env.local
    command: ["npm", "run", "server:dev"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - dev

  # Production service
  load-calculator:
    build:
      context: .
      dockerfile: Dockerfile
      # No build arguments to prevent API key exposure in image layers
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      # Runtime environment variables for production
      - USE_REAL_AERIAL_DATA=${USE_REAL_AERIAL_DATA:-false}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - AERIAL_PROVIDER=${AERIAL_PROVIDER:-google}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    env_file:
      - .env  # Load environment variables from .env file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - prod

  # Nginx reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - load-calculator
    restart: unless-stopped
    profiles:
      - prod
      - proxy

networks:
  default:
    driver: bridge

volumes:
  node_modules: